Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -46,38 +46,50 @@ jobs:
       - name: Run Application
         run: python main.py
         
-      # Генерація статусу білда
-      - name: Set status check
-        id: status-check
-        run: |
-          if [ $? -eq 0 ]; then
-            echo "Build and test completed successfully"
-            echo "::set-output name=status::success"
-          else
-            echo "Build and test failed"
-            echo "::set-output name=status::failure"
-          fi
-          
-      - name: Create status check
-        uses: actions/github-script@v5
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const { data: createCheckResult } = await github.checks.create({
-              owner: process.env.GITHUB_REPOSITORY_OWNER,
-              repo: process.env.GITHUB_REPOSITORY,
-              name: 'Build and Test',
-              head_sha: process.env.GITHUB_SHA,
-              status: 'completed',
-              conclusion: '${{ steps.status-check.outputs.status }}',
-              output: {
-                title: 'Build and Test',
-                summary: '${{ steps.status-check.outputs.status }}',
-              },
-            });
+        
+        
+        
+#       - name: Generate build status
+#         run: |
+#           # Generate build status here
+#           # Example: echo "Build succeeded" > build_status.txt
+#           echo "Build succeeded" > build_status.txt
 
-
-
+#       - name: Upload build status
+#         uses: actions/upload-artifact@v2
+#         with:
+#           name: Build Status
+#           path: build_status.txt
+        
+        
+#       # Генерація статусу білда
+#       - name: Set status check
+#         id: status-check
+#         run: |
+#           if [ $? -eq 0 ]; then
+#             echo "Build and test completed successfully"
+#             echo "::set-output name=status::success"
+#           else
+#             echo "Build and test failed"
+#             echo "::set-output name=status::failure"
+#           fi
+#       - name: Create status check
+#         uses: actions/github-script@v5
+#         with:
+#           github-token: ${{ secrets.GITHUB_TOKEN }}
+#           script: |
+#             const { data: createCheckResult } = await github.checks.create({
+#               owner: process.env.GITHUB_REPOSITORY_OWNER,
+#               repo: process.env.GITHUB_REPOSITORY,
+#               name: 'Build and Test',
+#               head_sha: process.env.GITHUB_SHA,
+#               status: 'completed',
+#               conclusion: '${{ steps.status-check.outputs.status }}',
+#               output: {
+#                 title: 'Build and Test',
+#                 summary: '${{ steps.status-check.outputs.status }}',
+#               },
+#             });
 
 #       # Генерація статусу білда 2
 #       - name: Set Build Status
